name: campus_connect
description: "CampusConnect - Campus Social & Event Management Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Networking
  dio: ^5.7.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^14.6.2
  
  # Storage
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.3
  
  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  
  # Image Picker
  image_picker: ^1.1.2
  
  # Socket.IO (for Phase 4 chat)
  socket_io_client: ^3.0.2
  
  # Utils
  intl: ^0.19.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
